---

- include: repository.yml
  tags: [postgresql, postgresql-configure]

- include: postgresql.yml
  tags: [postgresql, postgresql-install]

- include: repmgr.yml
  tags: [repmgr]

- include: wal-e.yml
  tags: [wal-e]

- include: configure.yml
  tags: [postgresql, postgresql-configure]

- include: tools.yml
  tags: postgresql
