---

- include: repository.yml
  tags: [postgresql, postgresql-configure]

- include: postgresql.yml
  tags: [postgresql, postgresql-install]

- include: repmgr.yml
  tags: [postgresql, repmgr]

- include: wal-e.yml
  tags: [postgresql, wal-e]

- include: configure.yml
  tags: [postgresql, postgresql-configure]

- include: tools.yml
  tags: [postgresql]

- include: munin.yml
  tags: [postgresql, postgresql-munin]
  when: munin_node_enabled
