---

- name: install perl and cpanm
  apt:
    pkg: "{{item}}"
    state: installed
    update-cache: yes
  with_items:
    - perl
    - curl
    - cpanminus
    - gettext
    - libdbi-perl
    - libdbd-pg-perl

- name: install munin db plugins dependencies
  cpanm: name='DBD::Pg' notest=True

- name: copy munin plugins to destination
  copy: src=files/munins/{{ item }} dest={{ munin_plugin_dest_path }}
  with_items:
    - pg__connections
    - postgres_locks
    - postgres_long_locks
    - postgresql_active_backends
    - postgresql_active_backends_by_database
    - postgresql_active_locks
    - postgresql_database_ratio
    - postgresql_database_size
    - postgresql_tablespace_size
    - postgresql_transactions

- name: fetch databases names from local postgres (exclude templates)
  shell:  >
    psql -t -c "
    SELECT datname
      FROM pg_database
     WHERE datistemplate = false;" | tr -d ' '
  sudo_user: postgres
  register: database_names

- name: copy multi-munin graph plugins to destination
  copy: >
    src=files/munins/{{ item[0] }}
    dest={{ munin_plugin_dest_path }}{{ item[0] }}{{ item[1] }}
  with_nested:
    - [postgres_block_read_, postgres_queries2_, postgres_queries3_,
       postgres_size_detail_, postgres_space_, postgres_tuplesratio_]
    - "{{ database_names.stdout_lines }}"
  when: database_names.stdout
