---

- template: src=sysctl-shm.conf.j2 dest=/etc/sysctl.d/30-postgresql-shm.conf
  notify: execute sysctl

- command: /sbin/sysctl -p /etc/sysctl.d/30-postgresql-shm.conf

- group: name={{ postgresql.group }}
- user: name={{ postgresql.user }} group={{ postgresql.group }} home=/var/lib/postgres shell=/bin/bash

- file: path={{ postgresql.config.data_dir }} state=directory owner={{ postgresql.user }}

- name: Install Postgresql server and client
  apt: pkg={{ item }}-{{ postgresql.version }} state=installed
  register: postgresql_install
  with_items:
    - postgresql
  tags:
    - packages

- name: Install development header files
  apt: pkg={{ item }} state=installed
  when: postgresql.install_development_headers == true
  with_items:
    - libpq-dev
  tags:
    - packages

- name: Install PostgreSQL config file
  template: src=postgresql/postgresql.conf.j2
            dest=/etc/postgresql/{{ postgresql.version }}/main/postgresql.conf
            owner={{ postgresql.user }} group={{ postgresql.group }}
  notify:
    - restart postgresql
  tags:
    - configuration

- template: src=postgresql/{{ item }}.j2
            dest=/etc/postgresql/{{ postgresql.version }}/main/{{ item }}
            owner={{ postgresql.user }} group={{ postgresql.group }}
  with_items:
    - pg_hba.conf
    - environment
  notify:
    - reload postgresql
  tags:
    - configuration
