---
- name: restart postgresql
  service: name=postgresql state=restarted

- name: reload postgresql
  service: name=postgresql state=reloaded

- name: execute sysctl
  command: /sbin/sysctl -p /etc/sysctl.d/30-postgresql-shm.conf

- name: restart monit
  service: name=monit state=restarted

- name: restart munin
  service: name=munin-node state=restarted
