#!/bin/bash

case $1 in
    config)
        cat <<EOF
graph_title Pending transactions
graph_vlabel pending txns
graph_category api
graph_info Shows the number of transactions in state PENDING.
credits.label Credits
credits.info Credits in state PENDING.
credits.warning 6000
debits.label Debits
debits.info Debits in state PENDING.
refunds.label Refunds
refunds.info Refunds in state PENDING.
reversals.label Reversals
reversals.info Reversals in state PENDING.
EOF
        exit 0;;
esac
pending=`psql -U balanced balanced -t <<EOF
SELECT count(*) FROM transactions2 t
INNER JOIN marketplaces mp
  ON t.marketplace_guid = mp.guid
WHERE mp.production = true
AND t.state IN ('PENDING')
GROUP BY t.type ORDER BY t.type;
EOF`

read credits debits refunds reversals <<<$(echo $pending)

if [ -z $credits ]; then credits=0; fi
if [ -z $debits ]; then debits=0; fi
if [ -z $refunds ]; then refunds=0; fi
if [ -z $reversals ]; then reversals=0; fi

echo credits.value $credits
echo debits.value $debits
echo refunds.value $refunds
echo reversals.value $reversals