#!/bin/bash

case $1 in
    config)
        cat <<EOF
graph_title PostgreSQL replication delay
graph_vlabel delay
graph_category postgresql
graph_info Shows the time since we last applied replication to the read slave (pg_last_xact_replay_timestamp)
delay.label Delay
delay.info Delay in seconds

DB01='balanced-db-01'
DB02='balanced-db-02'
if [ $HOSTNAME = $DB01 ];
then
    delay.critical 3600
fi
if [ $HOSTNAME = $DB02 ];
then
    delay.critical 60
fi

EOF
        exit 0;;
esac
locks=`psql -U postgres -t <<EOF
SELECT EXTRACT(EPOCH FROM NOW() - pg_last_xact_replay_timestamp())
EOF`

echo delay.value $locks